# Default values for k8s-challenge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: k8s-challenge

websiteDeployment:
  deploymentName: website-deployment
  containerName: ecom-web
  replicas: 2
  image: briangaber/ecom-web:v1
  port: 80
  appLabel: ecom-web
  tierLabel: frontend
  serviceName: website-service

databasePod: 
  podName: ecom-db
  image: mariadb
  port: 3306
  appLabel: ecom-db
  tierLabel: backend
  serviceName: mysql-service

storage:
  scName: aws-ssd-storage
  pvcName: mariadb-pv-claim