apiVersion: v1
kind: Pod
metadata:
  labels:
    app: ecom-web
    tier: backend
  name: ecom-db
spec:
  containers:
  - image: briangaber/ecom-db:v1
    name: ecom-db
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_USER
      value: "ecomuser"
    - name: MYSQL_PASSWORD
      value: "ecompassword"