apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pv-claim
  labels:
    app: ecom-web
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: aws-ssd-storage
  resources:
    requests:
      storage: 20Gi