apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.pvcName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: ecom-web
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.scName }}
  resources:
    requests:
      storage: 20Gi